### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by ScottGuymer** [philips-labs/terraform-cloudfoundry-grafana#19]
Can we build anything in to enable regular backups of the gf database?

**Comment by loafoe** [comment]
@ScottGuymer you can use https://github.com/philips-labs/hsdp-task-streaming-backup `hsdp_function` to set up a scheduled backup `Task` which will save dumps to an S3 bucket

This could be

**Comment by loafoe** [comment]
sorry, that unfinished sentence sneaked in somehow. The mentioned `hsdp_function` can be deployed alongside your Grafana instance (using Terraform):

```hcl
resource "hsdp_function" "psql_backup" {
  name         = "psql_backup"
  docker_image = "philipslabs/hsdp-task-streaming-backup:v0.2.0"
  command      = ["/app/backup.sh"]

  environment = {
    DB_HOST     = module.gf.credentials.host
    DB_PORT     = module.gf.credentials.port
    DB_USER     = module.gf.credentials.username
    DB_PASSWORD = module.gf.credentials.password
    DB_NAME     = module.gf.credentials.db_name

    BACKUP_NAME           = "backups/mydb"
    S3_ENDPOINT           = var.s3_endpoint
    S3_BUCKET             =  var.s3_bucket
    AWS_ACCESS_KEY_ID     = var.s3_access_key_id
    AWS_SECRET_ACCESS_KEY = var.s3_secret_access_key
  }

  schedule {
    run_every = "7d"
  }

  backend {
    credentials = module.siderite_backend.credentials
  }
}
```

**Comment by loafoe** [comment]
@ScottGuymer ...

**Comment by ScottGuymer** [comment]
I have not had time to look into this yet.. 

Ive also moved teams so not sure if I will.

@jdelucaa do you think this is a valuable addition?

**Comment by jdelucaa** [comment]
@ScottGuymer TBH I don't have that much knowledge of how Grafana works, but for the dashboards, we were planning to export them to JSON files and store them in VCS so we could restore them if needed, although I think it'd be nicer to have an automatic backup somewhere. For the users, since we are using IAM I don't think we are gonna need a backup.

**Comment by loafoe** [comment]
HSP brokered PostgreSQL databases have automated snapshots going back to max 35 days (default is 7 days). If this is not sufficient you can always take manual snapshots.. or use the above mentioned `hsdp_function` setup

**Comment by ScottGuymer** [comment]
Ah ok cool. And that's configured by default (the 7 days at least)?

**Comment by ScottGuymer** [comment]
@jdelucaa keeping as much of the config in code is a great way forward for sure.

**Comment by loafoe** [comment]
@ScottGuymer default snapshot retention is 7 days yes

**Comment by ScottGuymer** [comment]
This is probably overkill then!
