### ISSUE TITLE
Retention policy

### ISSUE THREAD

**Issue by manishkumar3001** [philips-labs/terraform-cloudfoundry-grafana#61]
The logs in grafana are stored in Prometheus database as of now we need to configure how many days of data we can keep .

I found that this can be done using prometheus  configuration ,Can we have this as a variable we can define?
--storage.tsdb.retention.time flag currently seems to define the retention period
https://prometheus.io/docs/prometheus/latest/storage/

**Comment by loafoe** [comment]
@manishkumar3001 these parameters are part of Prometheus and/or the Compactor component, both of which are managed under https://github.com/philips-labs/terraform-cloudfoundry-thanos . Please open a ticket under that repo.

**Comment by manishkumar3001** [comment]
done
